[package]
name = "sinepiac-lexer"
version = "0.1.0"
edition = "2021"

[dependencies]
logos = {workspace = true}
salsa = {workspace = true}
sinepiac-diagnostics = {workspace = true}
sinepiac-span = {workspace = true}
